global.crew[argument0].aggressivity = irandom(10)
global.crew[argument0].efficiency = irandom(10)
global.crew[argument0].loyalty = 5+irandom(3)
global.crew[argument0].extraversion = irandom(10)
global.crew[argument0].stealth = irandom(10)
global.crew[argument0].healthyness = irandom(10)
