global.current_date++

daily_event_selection()/*

kill_crewmember(global.crew[1],"infection")
kill_crewmember(global.crew[2],"infection")
kill_crewmember(global.crew[3],"infection")
kill_crewmember(global.crew[4],"infection")
kill_crewmember(global.crew[5],"infection")
kill_crewmember(global.crew[6],"infection")
kill_crewmember(global.crew[8],"infection")
kill_crewmember(global.crew[9],"infection")
kill_crewmember(global.crew[10],"infection")
kill_crewmember(global.crew[11],"infection")
kill_crewmember(global.crew[12],"infection")
kill_crewmember(global.crew[13],"infection")
kill_crewmember(global.crew[14],"infection")
kill_crewmember(global.crew[15],"infection")
kill_crewmember(global.crew[16],"infection")
kill_crewmember(global.crew[17],"infection")
kill_crewmember(global.crew[18],"infection")
kill_crewmember(global.crew[19],"infection")
kill_crewmember(global.crew[20],"infection")
kill_crewmember(global.crew[21],"infection")
kill_crewmember(global.crew[22],"infection")
kill_crewmember(global.crew[23],"infection")
kill_crewmember(global.crew[24],"infection")

kill_crewmember(global.crew[26],"infection")
kill_crewmember(global.crew[27],"infection")
kill_crewmember(global.crew[28],"infection")
kill_crewmember(global.crew[29],"infection")
kill_crewmember(global.crew[30],"infection")
kill_crewmember(global.crew[31],"infection")
kill_crewmember(global.crew[32],"infection")
kill_crewmember(global.crew[33],"infection")
kill_crewmember(global.crew[34],"infection")
kill_crewmember(global.crew[35],"infection")
kill_crewmember(global.crew[36],"infection")
kill_crewmember(global.crew[37],"infection")
kill_crewmember(global.crew[38],"infection")
kill_crewmember(global.crew[39],"infection")
kill_crewmember(global.crew[40],"infection")
kill_crewmember(global.crew[41],"infection")
kill_crewmember(global.crew[42],"infection")
kill_crewmember(global.crew[43],"infection")
kill_crewmember(global.crew[44],"infection")
kill_crewmember(global.crew[45],"infection")
kill_crewmember(global.crew[46],"infection")
kill_crewmember(global.crew[47],"infection")
kill_crewmember(global.crew[48],"infection")
kill_crewmember(global.crew[49],"infection")
kill_crewmember(global.crew[50],"infection")
kill_crewmember(global.crew[51],"infection")
kill_crewmember(global.crew[52],"infection")
kill_crewmember(global.crew[53],"infection")
kill_crewmember(global.crew[54],"infection")
kill_crewmember(global.crew[55],"infection")
kill_crewmember(global.crew[56],"infection")
kill_crewmember(global.crew[57],"infection")
kill_crewmember(global.crew[58],"infection")
kill_crewmember(global.crew[59],"infection")
 */

instance_create_layer(0,0,"fullscreenTextboxLayer", newDayScreen)

//start_next_daily_event()
