global.occupation[0]="Captain"
global.occupation[1]="First Mate"
global.occupation[2]="Second Mate"
global.occupation[3]="Third Mate"
global.occupation[4]="Fourth Mate"
global.occupation[5]="Boatswain"
global.occupation[6]="Boatswain's Mate"
global.occupation[7]="Surgeon"
global.occupation[8]="Surgeon's Mate"
global.occupation[9]="Carpenter"
global.occupation[10]="Carpenter's Mate"
global.occupation[11]="Cook"
global.occupation[12]="Butcher"
global.occupation[13]="Gunner"
global.occupation[14]="Gunner's Mate"
global.occupation[15]="Purser"
global.occupation[16]="Helmsman"
global.occupation[17]="Artist"
global.occupation[18]="Passenger"
global.occupation[19]="Steward"
global.occupation[20]="Midshipman"
global.occupation[21]="Topman"
global.occupation[22]="Seaman"
global.occupation[23]="Prisoner"


